# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build mart`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t mart`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system mart && \
          adduser --system -G mart mart

COPY dist/mart mart/
RUN chown -R mart:mart .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix mart --omit=dev -f install

CMD [ "node", "mart" ]
